---
apiVersion: v1
kind: Secret
metadata:
  name: testapp-testapp-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23Janus2/testapp-gateway-gitops
